### ISSUE TITLE
과제 피드백

### ISSUE THREAD

**Issue by DongHyunKIM-Hi** [guswlsdl0121/reboot-notification-system#4]
- 이건 별건 아닌데 현재 사용한 ResponseEntity 를 실무에서는 여기서 공통응답을 한번 더 묶어서 사용합니다. 해당 키워드로 검색해보시면 해당 내용 확인 하실 수 있습니다.
- 재입고 알람 설정한 사용자 ID 리스트를 좀 더 로직을 포함하고 있는 네이밍을 변경해주는 것이 좀 더 가독성이 좋을 것 같습니다. 단순 userIds 보단 좀 더 명확한 것이 좋을 것 같아요.
- ConcurrentHashMap 를 사용해서 동시성 문제를 잡은 것은 좋은 것 같습니다. 인상적이였습니다.
- 또한 코드 구조를 잘 잡으시네요? 코드 흐름이 매끄럽습니다. 사실 중간 중간 주석으로 설명이 있으면 좋겠다 라는 생각이 있었는데 흐름을 보면 또 딱히 필요 없을 것 같기도 합니다. 하지만 이후 기업 과제 할 때는 의도적으로 남겨주는 것이 좀 더 합격에 유리하지 않을까 생각합니다.
- Enum을 관리할 때는 일반적으로는 각각의 상태가 어떤 상태인지 명확하게 구분을 해주는 편입니다. 그래서 관용적으로 description 를 필드로 추가하여 사용하는 편입니다. 
- 전반적으로 코드 너무 깔끔하게 잘 작성하시네요. 너무 고생하셨습니다.

**Comment by guswlsdl0121** [comment]
피드백 감사드립니다!
